"""Added days to hire stats table

Revision ID: d64f08a430c5
Revises: 991ecb2bf269
Create Date: 2025-05-18 17:08:17.503233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64f08a430c5'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('avg_days_to_hire', sa.Float(), nullable=False),
    sa.Column('min_days_to_hire', sa.Float(), nullable=False),
    sa.Column('max_days_to_hire', sa.Float(), nullable=False),
    sa.Column('job_postings_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire_stats')
    # ### end Alembic commands ###
